const dictionary = {
  en: {
    search: "Search...",
    searchButton: "Search",
    HMICentreOfExcellenceCoE: "HMI Centre of Excellence (CoE)",
    HMIOverview: "HMI Overview",
    UXUI: "UX/UI",
    HMISoftwareDevelopment: "HMI Software Development",
    HMIVVSolutions: "HMI V&V Solutions",
    HMIAccelerators: "HMI Accelerators",
    HMISoftwareProducts: "HMI Software Products",
    PRESENTATION: "PRESENTATION",
    VIDEO: "VIDEO",
    CASESTUDY: "CASE STUDY",
    VoiceBiometry: "Voice Biometry",
    HMIAnalytics: "HMI Analytics",
    HMIAccelarators: "HMI Accelarators",
  },
  de: {
    search: "Suchen...",
    searchButton: "Suchen",
    HMICentreOfExcellenceCoE: "HMI-Zentrum für Exzellenz (CoE)",
    HMIOverview: "HMI-Oberblick",
    UXUI: "UX/UI",
    HMISoftwareDevelopment: "HMI-Softwareentwicklung",
    HMIVVSolutins: "HMI V&V-Lösungen",
    HMIAccelerators: "HMI-Beschleuniger",
    HMISoftwareProducts: "HMI-Softwareprodukte",
    PRESENTATION: "PRÄSENTATION",
    VIDEO: "VIDEOde",
    CASESTUDY: "FALLSTUDIE",
    VoiceBiometry: "Stimmbiometrie",
    HMIAnalytics: "HMI-Analytik",
    HMIAccelarators: "HMI-Beschleuniger",
  },
};

export default dictionary;
